SELECT A.PRODUCT_ID, A.PRODUCT_NAME, sum(PRICE * AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT as A
JOIN FOOD_ORDER as B
on A.PRODUCT_ID=B.PRODUCT_ID
where DATE_FORMAT(B.PRODUCE_DATE,'%Y-%m')='2022-05'
group by A.PRODUCT_ID
order by TOTAL_SALES desc, A.PRODUCT_ID