with YEARLY as (
    select YEAR(DIFFERENTIATION_DATE) as YEAR , MAX(SIZE_OF_COLONY) as MAX_COLONY_SIZE
    from ECOLI_DATA
    group by YEAR)
    
select YEAR(a.DIFFERENTIATION_DATE) as YEAR , (YEARLY.MAX_COLONY_SIZE-a.SIZE_OF_COLONY) as YEAR_DEV, a.ID
from ECOLI_DATA as a
JOIN YEARLY
on YEAR(a.DIFFERENTIATION_DATE) = YEARLY.YEAR
order by YEAR,YEAR_DEV;