SELECT b.BOOK_ID as ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
from BOOK as b
JOIN AUTHOR as a
on b.AUTHOR_ID=a.AUTHOR_ID
where b.CATEGORY='경제'
order by PUBLISHED_DATE;